### ISSUE TITLE
Setup CI to automatically bump golang package on minor version

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-smoke-tests-release#10]
We should always be trying to include the latest patch release of https://github.com/bosh-packages/golang-release.

**Comment by will-gant** [comment]
Hey there. In case, by freak chance, you or someone else is working on this (or is about to) I'm taking a look at this now on behalf of SAP.

**Comment by ctlong** [comment]
Looks great, thanks @will-gant! One more step that would be awesome to have in the pipeline would be to remove the old golang packages after the new ones are vendored in.

**Comment by will-gant** [comment]
No worries. Yeah, I'll take a look at that now.

**Comment by will-gant** [comment]
Made another PR. Think you were right with your suggestion earlier on vendoring `golang-1-linux` and `golang-1-windows`.

Also don't forget cloudfoundry/cf-smoke-tests#80

**Comment by ctlong** [comment]
All merged and flown. Now just waiting to see it pass the pipeline.

**Comment by ctlong** [comment]
Everything looks good!

Thanks again @will-gant 🙏
