### ISSUE TITLE
Use the cf-cli-release instead of packaging the cli

### ISSUE THREAD

**Issue by XenoPhex** [cloudfoundry/cf-smoke-tests-release#3]
The CF CLI team is now releasing [a bosh release for the cli](https://github.com/bosh-packages/cf-cli-release). We'd like the smoke tests to consume the cli vai this release as opposed to packaging the cli itself.

**Comment by XenoPhex** [comment]
We've added a bosh.io release: https://bosh.io/releases/github.com/bosh-packages/cf-cli-release

**Comment by heyjcollins** [comment]
Sounds great. 
One question though -- 
What happens to smokes if/when run to verify a commercial PAS install on an air-gapped environment?

**Comment by davewalter** [comment]
Closing old issue.
