### ISSUE TITLE
Windows smoke-tests timeout when using HAProxy + HTTPS

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-smoke-tests-release#5]
We recently started running windows smoke tests in our CI with Windows Server 2016 stemcells on GCP. For most of our environments the smoke tests are passing but for one "internetless" environment the test always fails with the following error:

```
           [2018-11-04 23:10:28.90 (UTC)]> cf auth smoke_tests [REDACTED]   
             
           [2018-11-04 23:10:33.91 (UTC)]> cf auth smoke_tests [REDACTED]   
           Failure [0.000 seconds]  
           [AfterSuite] AfterSuite   
           c:/var/vcap/packages/smoke_tests_windows/src/github.com/cloudfoundry/cf-smoke-tests/smoke/logging/init_test.go:28  
             
             Timed out after 5.001s.  
             Expected process to exit.  It did not.  
             
             c:/var/vcap/packages/smoke_tests_windows/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/workflowhelpers/internal/cf_auth.go:30 
```

Here are our findings so far:

- Only fails on "internetless" env, main difference seems to be HAProxy is deployed in front of GoRouters rather than an LB. Also outbound egress is disabled.
- Smoke tests are failing due to `cf auth USERNAME PASSWORD` taking longer than hardcoded timeout of 5 seconds
- Running `cf auth` from Linux VMs in the same deployments returns in less than half a second
- Running `cf auth` from Windows cell takes ~20 seconds
  - `bosh ssh` onto windows cell
  - `powershell`
  - `$env:PATH="c:\var\vcap\packages\cf_cli_windows;$env:PATH"`
  - `cf api ... ; cf auth ...`
- Setting `cf api http://...` rather than `https` returns in less than half a second rather than ~20 seconds with `https`
- Adding the `--skip-ssl-validation` flag with an `https` API endpoint also returns in less than half a second
- Changing cipher suites on HAProxy VM didn't seem to have any effect

So the issue seems to be related to verifying TLS certificates but only occurs against HAProxy deployments (or envs without internet access).

**Comment by heyjcollins** [comment]
Hey @ljfranklin -
We updated cf-test-helpers in smoketests last week and I believe the timeout is now 30 seconds.
Are you still experiencing this particular issue in your internetless envs?

Let us know when you have a chance.

Thanks!

Josh and Relint-Team

**Comment by ljfranklin** [comment]
@heyjcollins in this case the previous 5 second timeout when running `cf auth` was what allowed us to catch this error. The delay was due to some OCSP issue in Windows that we would like to get fixed in the platform. More context here: https://www.pivotaltracker.com/n/projects/1369466/stories/161348722.

So no issue with smoke tests I guess, this is a platform issue.

**Comment by heyjcollins** [comment]
Ok @ljfranklin ,

Given it's a latency issue for internetless environment - not a complete failure to auth - the foundation is still usable, albeit slow to respond, I'm going to go ahead and close this issue out.

Please comment and reopen if you'd like to continue to dialogue with me/RelInt.

Cheers,

Josh
