### ISSUE TITLE
Unexpected error: mkdir /var/vcap/data/smoke_tests/.cf: permission denied 

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-smoke-tests-release#6]
When running smoke tests as a collocated errand, with bpm enabled, we are seeing the error message from the title 

```
Unexpected error: mkdir /var/vcap/data/smoke_tests/.cf: permission denied 
```

When digging into this a bit with @xoebus it looked like it might be caused because in the [bpm config](https://github.com/cloudfoundry/cf-smoke-tests-release/blob/3a1e78ca2e90fc50d203e032df52e007733244cd/jobs/smoke_tests/templates/bpm.yml.erb) it's missing the [`ephemeral_disk`](https://github.com/cloudfoundry-incubator/bpm-release/blob/fe3412c31a1107f7a8688899eaa90386838fd569/docs/config.md) property set to true

It's strange, though, that we're seeing this failure intermittently? So take our analysis with a grain of salt, however it does appear this configuration should be there.

We should also consider the upgrade case where someone has run the co-located errand without BPM enabled (errand runs as root), the `/var/vcap/data/smoke_tests/.cf` dir was created by root, then BPM gets turned on and the next errand runs as `vcap`. Maybe the smoke tests should set `CF_HOME` to a temp dir or similar?

**Comment by heyjcollins** [comment]
We've been communicating about this directly using our mouths and a bit over slack.
We believe we've resolved this issue in cf-smoke-tests-release v40.0.20 so I'm going to close this issue.
Please reopen, or log a-new if you see this error again.  
Thank you!
